{application,server,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"server"},
              {modules,['Elixir.ShoppingListServer',
                        'Elixir.ShoppingListStore','Elixir.User',
                        'Elixir.UserStore']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
